### ISSUE TITLE
Demo doesn't work when access over https

### ISSUE THREAD

**Issue by follower** [pigshell/pigshell#13]
Demo fails due to requests being via http:// rather than https:// when accessed via https://pigshell.com/

**Comment by ganeshv** [comment]
Yes, this is a deployment issue. Please use http://pigshell.com as a workaround, until I set up a redirect from https to http.

**Comment by ganeshv** [comment]
Fixed now. https://pigshell.com and https://pigshell.com/v/* now redirect to the http site. The reason we use http is we commonly access http resources in pigshell (especially from the localhost proxy) and most browsers these days balk at https pages accessing http resources.
