### ISSUE TITLE
Facebook connected. Friends now showing.

### ISSUE THREAD

**Issue by mrdrozdov** [pigshell/pigshell#14]
It's not only friends. Every directory is missing any valuable data. I'm a fairly active facebook user (1000+ friends).

**Comment by ganeshv** [comment]
Unfortunately, Facebook have changed their API considerably since FacebookFS was written. Most importantly, apps cannot get the friends list any more. That API now returns only those friends who are also using the app.

**Comment by mrdrozdov** [comment]
gif me sad :sob:

**Comment by mrdrozdov** [comment]
should add support for use fb data that facebook allows you to export!

**Comment by ganeshv** [comment]
Have you seen the FB data that Facebook exports? First of all, it's an offline process where you initiate a request and sometime later you get a notification to download a zip file. The friends list there is one html file with the first name and last name of each friend. That's IT. No email address, no location, no phone number, no nothing.

**Comment by mrdrozdov** [comment]
You bring up some good points. :(
